/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as circom from "./circom";
export type { circom };
import type * as src from "./src";
export type { src };
