/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVerifier,
  IVerifierInterface,
} from "../../../contracts/src/IVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "IVerifier.Hash",
        name: "_merkleRoot",
        type: "bytes32",
      },
    ],
    name: "commit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "disableModel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "IVerifier.Hash",
        name: "_commitmentId",
        type: "bytes32",
      },
    ],
    name: "getCommitment",
    outputs: [
      {
        components: [
          {
            internalType: "IVerifier.Hash",
            name: "id",
            type: "bytes32",
          },
          {
            internalType: "IVerifier.Hash",
            name: "modelContentId",
            type: "bytes32",
          },
          {
            internalType: "IVerifier.Hash",
            name: "merkleRoot",
            type: "bytes32",
          },
          {
            internalType: "IVerifier.Hash",
            name: "challenge",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "difficulty",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "proverAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isRevealed",
            type: "bool",
          },
        ],
        internalType: "struct IVerifier.Commitment",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_offset",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_limit",
        type: "uint32",
      },
    ],
    name: "getCommitmentsOfModel",
    outputs: [
      {
        internalType: "IVerifier.Hash[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_offset",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_limit",
        type: "uint32",
      },
    ],
    name: "getCommitmentsOfProver",
    outputs: [
      {
        internalType: "IVerifier.Hash[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDifficulty",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getModel",
    outputs: [
      {
        components: [
          {
            internalType: "IVerifier.Hash",
            name: "contentId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "address",
            name: "ownerAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
        ],
        internalType: "struct IVerifier.Model",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "IVerifier.Hash",
        name: "_modelContentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "_modelName",
        type: "string",
      },
      {
        internalType: "string",
        name: "_modelDescription",
        type: "string",
      },
      {
        internalType: "address",
        name: "_modelOwnerAddress",
        type: "address",
      },
    ],
    name: "registerModel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "IVerifier.Hash",
        name: "_commitmentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "_merkleProofs",
        type: "bytes32[]",
      },
      {
        internalType: "bool[]",
        name: "_proofFlags",
        type: "bool[]",
      },
      {
        internalType: "bytes32[]",
        name: "_leaves",
        type: "bytes32[]",
      },
    ],
    name: "reveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "IVerifier.Hash",
        name: "_commitmentId",
        type: "bytes32",
      },
    ],
    name: "updateChallenge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_difficulty",
        type: "uint8",
      },
    ],
    name: "updateDifficulty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_modelName",
        type: "string",
      },
      {
        internalType: "string",
        name: "_modelDescription",
        type: "string",
      },
    ],
    name: "updateModel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "commitmentId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "a",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2][2]",
            name: "b",
            type: "uint256[2][2]",
          },
          {
            internalType: "uint256[2]",
            name: "c",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[16]",
            name: "input",
            type: "uint256[16]",
          },
        ],
        internalType: "struct IVerifier.Zkp[]",
        name: "zkps",
        type: "tuple[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[16]",
                name: "input",
                type: "uint256[16]",
              },
            ],
            internalType: "struct IVerifier.Zkp",
            name: "zkp",
            type: "tuple",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IVerifier.ZkpWithValidity[]",
        name: "zkpVerifications",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IVerifierInterface {
    return new utils.Interface(_abi) as IVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVerifier {
    return new Contract(address, _abi, signerOrProvider) as IVerifier;
  }
}
