// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.19;

/**
 * @title Interface of verifier contract auto-generated by Circom
 * @author Seiya Kobayashi
 */
interface ICircomVerifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) external view returns (bool r);
}
