/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IVerifier {
  export type ModelStruct = {
    contentId: PromiseOrValue<BytesLike>;
    name: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    ownerAddress: PromiseOrValue<string>;
    isDisabled: PromiseOrValue<boolean>;
  };

  export type ModelStructOutput = [string, string, string, string, boolean] & {
    contentId: string;
    name: string;
    description: string;
    ownerAddress: string;
    isDisabled: boolean;
  };

  export type ModelArrayElementStruct = {
    contentId: PromiseOrValue<BytesLike>;
    name: PromiseOrValue<string>;
  };

  export type ModelArrayElementStructOutput = [string, string] & {
    contentId: string;
    name: string;
  };

  export type MerkleProofStruct = {
    leaf: PromiseOrValue<BytesLike>;
    proof: PromiseOrValue<BytesLike>[];
  };

  export type MerkleProofStructOutput = [string, string[]] & {
    leaf: string;
    proof: string[];
  };

  export type ZkpStruct = {
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ];
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    input: PromiseOrValue<BigNumberish>[];
  };

  export type ZkpStructOutput = [
    [BigNumber, BigNumber],
    [[BigNumber, BigNumber], [BigNumber, BigNumber]],
    [BigNumber, BigNumber],
    BigNumber[]
  ] & {
    a: [BigNumber, BigNumber];
    b: [[BigNumber, BigNumber], [BigNumber, BigNumber]];
    c: [BigNumber, BigNumber];
    input: BigNumber[];
  };

  export type ZkpWithValidityStruct = {
    zkp: IVerifier.ZkpStruct;
    isValid: PromiseOrValue<boolean>;
  };

  export type ZkpWithValidityStructOutput = [
    IVerifier.ZkpStructOutput,
    boolean
  ] & { zkp: IVerifier.ZkpStructOutput; isValid: boolean };
}

export interface VerifierInterface extends utils.Interface {
  functions: {
    "commit(bytes32,bytes32,bytes32)": FunctionFragment;
    "disableModel(bytes32)": FunctionFragment;
    "getModel(bytes32)": FunctionFragment;
    "getModels(uint32,uint32)": FunctionFragment;
    "getModelsByOwnerAddress(address,uint32,uint32)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerModel(bytes32,string,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reveal(uint256,(bytes32,bytes32[])[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateModel(bytes32,string,string)": FunctionFragment;
    "verify(uint256,(uint256[2],uint256[2][2],uint256[2],uint256[16])[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "commit"
      | "disableModel"
      | "getModel"
      | "getModels"
      | "getModelsByOwnerAddress"
      | "owner"
      | "registerModel"
      | "renounceOwnership"
      | "reveal"
      | "transferOwnership"
      | "updateModel"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "commit",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disableModel",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getModel",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getModels",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getModelsByOwnerAddress",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerModel",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reveal",
    values: [PromiseOrValue<BigNumberish>, IVerifier.MerkleProofStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateModel",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [PromiseOrValue<BigNumberish>, IVerifier.ZkpStruct[]]
  ): string;

  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getModel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getModels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getModelsByOwnerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "ModelDisabled(bytes32,address)": EventFragment;
    "ModelRegistered(bytes32,address)": EventFragment;
    "ModelUpdated(bytes32,address,string,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ModelDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModelRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModelUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface ModelDisabledEventObject {
  contentId: string;
  ownerAddress: string;
}
export type ModelDisabledEvent = TypedEvent<
  [string, string],
  ModelDisabledEventObject
>;

export type ModelDisabledEventFilter = TypedEventFilter<ModelDisabledEvent>;

export interface ModelRegisteredEventObject {
  contentId: string;
  ownerAddress: string;
}
export type ModelRegisteredEvent = TypedEvent<
  [string, string],
  ModelRegisteredEventObject
>;

export type ModelRegisteredEventFilter = TypedEventFilter<ModelRegisteredEvent>;

export interface ModelUpdatedEventObject {
  contentId: string;
  ownerAddress: string;
  name: string;
  description: string;
}
export type ModelUpdatedEvent = TypedEvent<
  [string, string, string, string],
  ModelUpdatedEventObject
>;

export type ModelUpdatedEventFilter = TypedEventFilter<ModelUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Verifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    commit(
      commitmentModel: PromiseOrValue<BytesLike>,
      commitmentData: PromiseOrValue<BytesLike>,
      commitmentResults: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [IVerifier.ModelStructOutput] & { model: IVerifier.ModelStructOutput }
    >;

    getModels(
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IVerifier.ModelArrayElementStructOutput[]] & {
        paginatedModels: IVerifier.ModelArrayElementStructOutput[];
      }
    >;

    getModelsByOwnerAddress(
      ownerAddress: PromiseOrValue<string>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IVerifier.ModelArrayElementStructOutput[]] & {
        paginatedModels: IVerifier.ModelArrayElementStructOutput[];
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registerModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reveal(
      commitmentId: PromiseOrValue<BigNumberish>,
      merkleProofs: IVerifier.MerkleProofStruct[],
      overrides?: CallOverrides
    ): Promise<[string[]] & { verifiedNodes: string[] }>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verify(
      commitmentId: PromiseOrValue<BigNumberish>,
      zkps: IVerifier.ZkpStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  commit(
    commitmentModel: PromiseOrValue<BytesLike>,
    commitmentData: PromiseOrValue<BytesLike>,
    commitmentResults: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableModel(
    modelContentId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getModel(
    modelContentId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IVerifier.ModelStructOutput>;

  getModels(
    offset: PromiseOrValue<BigNumberish>,
    limit: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IVerifier.ModelArrayElementStructOutput[]>;

  getModelsByOwnerAddress(
    ownerAddress: PromiseOrValue<string>,
    offset: PromiseOrValue<BigNumberish>,
    limit: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IVerifier.ModelArrayElementStructOutput[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  registerModel(
    modelContentId: PromiseOrValue<BytesLike>,
    modelName: PromiseOrValue<string>,
    modelDescription: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reveal(
    commitmentId: PromiseOrValue<BigNumberish>,
    merkleProofs: IVerifier.MerkleProofStruct[],
    overrides?: CallOverrides
  ): Promise<string[]>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateModel(
    modelContentId: PromiseOrValue<BytesLike>,
    modelName: PromiseOrValue<string>,
    modelDescription: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verify(
    commitmentId: PromiseOrValue<BigNumberish>,
    zkps: IVerifier.ZkpStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    commit(
      commitmentModel: PromiseOrValue<BytesLike>,
      commitmentData: PromiseOrValue<BytesLike>,
      commitmentResults: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { commitmentId: BigNumber; challenge: string }
    >;

    disableModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelStructOutput>;

    getModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelStructOutput>;

    getModels(
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelArrayElementStructOutput[]>;

    getModelsByOwnerAddress(
      ownerAddress: PromiseOrValue<string>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelArrayElementStructOutput[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    registerModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelStructOutput>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    reveal(
      commitmentId: PromiseOrValue<BigNumberish>,
      merkleProofs: IVerifier.MerkleProofStruct[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IVerifier.ModelStructOutput>;

    verify(
      commitmentId: PromiseOrValue<BigNumberish>,
      zkps: IVerifier.ZkpStruct[],
      overrides?: CallOverrides
    ): Promise<IVerifier.ZkpWithValidityStructOutput[]>;
  };

  filters: {
    "ModelDisabled(bytes32,address)"(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null
    ): ModelDisabledEventFilter;
    ModelDisabled(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null
    ): ModelDisabledEventFilter;

    "ModelRegistered(bytes32,address)"(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null
    ): ModelRegisteredEventFilter;
    ModelRegistered(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null
    ): ModelRegisteredEventFilter;

    "ModelUpdated(bytes32,address,string,string)"(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null,
      name?: null,
      description?: null
    ): ModelUpdatedEventFilter;
    ModelUpdated(
      contentId?: PromiseOrValue<BytesLike> | null,
      ownerAddress?: PromiseOrValue<string> | null,
      name?: null,
      description?: null
    ): ModelUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    commit(
      commitmentModel: PromiseOrValue<BytesLike>,
      commitmentData: PromiseOrValue<BytesLike>,
      commitmentResults: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getModels(
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getModelsByOwnerAddress(
      ownerAddress: PromiseOrValue<string>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registerModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reveal(
      commitmentId: PromiseOrValue<BigNumberish>,
      merkleProofs: IVerifier.MerkleProofStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verify(
      commitmentId: PromiseOrValue<BigNumberish>,
      zkps: IVerifier.ZkpStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    commit(
      commitmentModel: PromiseOrValue<BytesLike>,
      commitmentData: PromiseOrValue<BytesLike>,
      commitmentResults: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getModel(
      modelContentId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getModels(
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getModelsByOwnerAddress(
      ownerAddress: PromiseOrValue<string>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reveal(
      commitmentId: PromiseOrValue<BigNumberish>,
      merkleProofs: IVerifier.MerkleProofStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateModel(
      modelContentId: PromiseOrValue<BytesLike>,
      modelName: PromiseOrValue<string>,
      modelDescription: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verify(
      commitmentId: PromiseOrValue<BigNumberish>,
      zkps: IVerifier.ZkpStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
