/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "CustomVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CustomVerifier__factory>;
    getContractFactory(
      name: "CustomVerifierFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CustomVerifierFactory__factory>;
    getContractFactory(
      name: "ICircomVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICircomVerifier__factory>;
    getContractFactory(
      name: "ICustomVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICustomVerifier__factory>;
    getContractFactory(
      name: "ICustomVerifierFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICustomVerifierFactory__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "CustomVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CustomVerifier>;
    getContractAt(
      name: "CustomVerifierFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CustomVerifierFactory>;
    getContractAt(
      name: "ICircomVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICircomVerifier>;
    getContractAt(
      name: "ICustomVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICustomVerifier>;
    getContractAt(
      name: "ICustomVerifierFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICustomVerifierFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
